name: Collect Dott Positions

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas requests

    - name: Run the collector
      run: python py_trigger.py

    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add dott_positions.csv
        git commit -m "Data update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        git config --local --unset-all http.https://github.com/.extraheader
        git remote -v
        git push origin HEAD:${{ github.ref }}
