name: Collect Dott Positions

on:
  schedule:
    - cron:  '*/10 * * * *'   # Toutes les 10 minutes
  workflow_dispatch:           # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas requests

    - name: Run the collector
      run: python collect_dott.py

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add dott_positions.csv
        git commit -m "Data update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
